In [100]:
import numpy as np
import matplotlib.pyplot as plt
from Functions import *

In [101]:
dxdt = lambda t,x: t*x
x0 = 1

In [102]:
x_true = lambda t: np.exp(t**2/2)

In [103]:
x_true(2)

7.38905609893065

In [104]:
eu = EulerODE(dxdt, x0, [0, 2], 40)
eu[1][np.where(eu[0] == 2)] # Find x(2) for the Euler method

array([6.61146382])

In [105]:
he = HeunODE(dxdt, x0, [0, 2], 20)
he[1][np.where(he[0] == 2)] # Find x(2) for the Heun method

array([7.34383122])

In [106]:
f = lambda t,x: t*x
df = lambda t,x,dx: x + dx
ta = TaylorOrder2(f, df, x0, 0, 2, 20)
ta[1][np.where(ta[0] == 2)] # Find x(2) for the Taylor method

array([7.1154183])

In [112]:
RungeKutta4(dxdt, [0, 2], x0, 10)

(array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ]),
 array([1.        , 1.02020133, 1.08328699, 1.19721701, 1.37712642,
        1.64871668, 2.05441881, 2.66441399, 3.59652192, 5.0527736 ,
        7.38822484]))